version: '3.11'

volumes:
  postgresql:
  media_value:

services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: 'collection'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - file_manager

  backend:
    image: backend:latest
    ports:
      - 8080:8080
    volumes:
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - POSTGRES_PORT=5432
    networks:
      - file_manager
    restart: always

networks:
  file_manager:
    external: true